#!/bin/bash

set -e

# If using venv to install, active it before running
if [ -d ".venv" ]
then
    source .venv/bin/activate
fi

# Make sure uvicorn is installed
command -v uvicorn >/dev/null 2>&1 || { echo >&2 "uvicorn required to run this server. Please first run the setup procedure. Aborting."; exit 1; }
# Make sure you are in directory of script
cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

# Run server command
uvicorn e2emessenger.server.server:app --host 0.0.0.0
