#!/bin/bash

set -e

# Make sure python3 is installed
command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is required for setup. Aborting."; exit 1; }
# Make sure you are in directory of script
cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

# Install virtualenv if not installed
python3 -m pip install --user virtualenv

# Setup a new virtualenv
python3 -m venv .venv
# Activate new virtualenv
source .venv/bin/activate
# Install all required packages for app
pip install -r requirements.txt
